language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# travis ci server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # directory for deployment files. for deployment Jar, appspec(codedeploy), script files are needed
  - cp scripts/*.sh before-deploy/ # script file
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # compress all the files in the dir as a zip.
  - cd ../ && mkdir -p deploy # create dir
  - mv before-deploy/before-deploy.zip deploy/toy-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-cannedcoffee-deploy
    region: us-east-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-cannedcoffee-deploy
    key: toy-springboot.zip
    bundle_type: zip
    application: springboot-cannedcoffee-codedeploy
    deployment_group: springboot-cannedcoffee-group
    region: us-east-2
    wait_until_deployed: true


before_install:
  - chmod +x gradlew

# mail notification when CI is successful
notifications:
  email:
    recipients:
      - hsbang.thom@gmail.com