language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# travis ci server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-cannedcoffee *
  - mkdir -p deploy
  - mv springboot-cannedcoffee.zip deploy/springboot-cannedcoffee.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-cannedcoffee-deploy
    region: us-east-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-cannedcoffee-deploy
    application: springboot-cannedcoffee-codedeploy
    deployment_group: springboot-cannedcoffee-group
    region: us-east-2
    key: deploy/springboot-cannedcoffee.zip
    wait_until_deployed: true


before_install:
  - chmod +x gradlew

# mail notification when CI is successful
notifications:
  email:
    recipients:
      - hsbang.thom@gmail.com