version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # kill application that is not assigned to nginx
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # new application starts with a port
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # check if new app has cleanly been launched
      timeout: 60
      runas: ec2-user
